### ISSUE TITLE
Cerebral stamp

### ISSUE THREAD

**Issue by ericelliott** [stampit-org/react-stampit#11]
I'm thinking of using [Cerebral](https://github.com/christianalfoni/cerebral) for my next app. It seems like it would be easy to create a Cerebral component stamp that could augment any container component by composing it in.

Thoughts?

**Comment by troutowicz** [comment]
Since react-stampit provides the POJO shortcut for mixins, Cerebral's mixin should "just work" as a stamp mixin. :)

**Comment by ericelliott** [comment]
Cool. =)
