### ISSUE TITLE
Hello World App Example

### ISSUE THREAD

**Issue by ericelliott** [stampit-org/react-stampit#12]
See [react-hello](https://github.com/ericelliott/react-hello) for example. Should probably belong in its own repo, and just get linked to from the react-stampit docs.

**Comment by troutowicz** [comment]
:+1: 

Edit: I'll knock this out tonight hopefully.

**Comment by troutowicz** [comment]
@ericelliott https://github.com/stampit-org/react-hello

**Comment by ericelliott** [comment]
:+1:

**Comment by ericelliott** [comment]
Did we add a link to it in our docs yet?

**Comment by troutowicz** [comment]
Just added it. :+1:
