### ISSUE TITLE
Lets use webpack

### ISSUE THREAD

**Issue by troutowicz** [stampit-org/react-stampit#18]
We should come up with some webpack configs that can be used in all stampit projects.

**Comment by ericelliott** [comment]
I believe we already did that in the [prod-module-boilerplate](https://github.com/ericelliott/prod-module-boilerplate). I would be thrilled if we did it the same way here.

**Comment by troutowicz** [comment]
Awesome :+1:

**Comment by troutowicz** [comment]
See #20
