### ISSUE TITLE
Simplify README

### ISSUE THREAD

**Issue by troutowicz** [stampit-org/react-stampit#23]
We should move the API documentation into a seperate file in docs/.

On a different but related note, I think the `isStamp` static utility method should be removed and just made available as a utility. This will move us closer to conforming to the future standard stamp spec.

``` js
import { isStamp } from 'react-stampit/utils';
```

Maybe another file should be made in docs/ for mentioning available utilities?

**Comment by ericelliott** [comment]
Agreed.
