### ISSUE TITLE
Composing Refs

### ISSUE THREAD

**Issue by joshdmiller** [stampit-org/react-stampit#29]
Hello! I'm trying to create a mixin that components that need to connect to a Flux-like store can use, but I'm confused between `stampit` and `react-stampit` lands. I would expect the following (truncated) code to work, but `this.stores` is undefined at the comment below:

``` js
import React from 'react';
import stampit from 'stampit';
import rStampit from 'react-stampit';

// the mixin
var StoreConnector = stampit({
  refs: {
    stores: []
  },

  methods: {
    componentWillMount () {
      // this.stores is undefined, though it's defined above and in the other stamp
      this.stores.forEach( store => /* ... */ );
    }
  },

  init: function () {
    // Results only in `{ state: {} }`
    console.log( 'this', this );
    this.state = this.getState();
  }
});

// the component
var Component = rStampit( React, {
  stores: [ store ],

  getState () {
    return {
      name: store.getValue()
    };
  },

  render () {
    // This works because `getState` is called by the mixin's `init`, as expected.
    return (<div>The name is <b>{this.state.name}</b></div>);
  }
}).compose( StoreConnector );
```

I am having difficulty mixing in any refs, it would seem. Am I approaching this incorrectly? Would it be better to just use stampit?

**Comment by BerkeleyTrue** [comment]
refs other than ref.state are not mixed in ([reference](https://github.com/stampit-org/react-stampit/blob/master/src/index.js#L127)). Instead add the store object during init method. This also ensures that each new instance receives a unique array.

``` js
  init: function () {
    this.stores = [];
    this.state = this.getState();
  }
```

**Comment by joshdmiller** [comment]
Thanks for responding, @BerkeleyTrue! You're right about the initialization, though it won't actually solve the problem because the array needs to be defined on the component using the mixin. The only reason it is defined on the mixin is to prevent undefined errors in the other methods if the component didn't define it.

But to have to use `init`on the "child" would really defeat the simplicity of react-stampit because it would require a much more verbose syntax. Surely there's a way to easily mix in functionality like this; any ideas?

**Comment by troutowicz** [comment]
I'm looking into it. :)

**Comment by troutowicz** [comment]
What about something like this?

``` js
import React from 'react';
import stampit from 'react-stampit';

const storeMock = {
  getState() {
    return { name: 'foo' };
  },
};

// the mixin
const StoreConnector = {
  componentWillMount() {
    this.stores = [];
  },

  componentDidMount() {
    this.stores.forEach(store => {
      // Do something immediately after render
    });
  },
};

// the component
const Component = stampit(React, {
  state: { name: storeMock.getState().name },

  componentWillMount() {
    this.stores = [ storeMock ];
  },

  render() {
    return (<div>The name is <b>{ this.state.name }</b></div>);
  },
}).compose(StoreConnector);

console.log(React.renderToStaticMarkup(<Component />));
```

**Comment by BerkeleyTrue** [comment]
> But to have to use init on the "child" would really defeat the simplicity of react-stampit 

I've advocated for this here: https://github.com/stampit-org/react-stampit/issues/21

It is a difficult problem because react has specific properties that need to be merged or deduped.

**Comment by joshdmiller** [comment]
@BerkeleyTrue I read through #21 before I submitted this issue and learned a lot from that conversation. I agree that it's a difficult problem.

@troutowicz Thanks for the suggestion! That's a little closer to what I was looking for, but the particulars wouldn't work. I'm essentially porting [this code](https://github.com/gaearon/flux-react-router-example/blob/598472175e13554da97706c8cacb05a65cfadbbe/scripts/utils/connectToStores.js) to an an environment that uses RxJS instead of the dispatchers and callbacks and stampit instead of classes. Starting with your example, I came up with something like this:

**Mixin**

``` js
var StoreConnector = stampit()
  .methods({
    componentWillMount () {
      this.storeSubscriptions = [];
      this.stores.forEach( store =>
       this.storeSubscriptions.push( store.subscribe( () => this.handleStoreUpdates() ) )
      );
    },

    componentWillReceiveProps ( props ) {
      this.setState( this.getState( props ) );
    },

    componentWillUnmount () {
      this.storeSubscriptions.forEach( dispose => dispose() );
    },

    handleStoreUpdates () {
      this.setState( this.getState( this.props ) );
    },
  })

  .init( function () {
    if ( this.getStores ) {
      this.stores = this.getStores();
    } else {
      this.stores = [];
    }

    if ( ! this.getState ) {
      this.getState = function () { return {}; };
    }

    this.state = this.getState();
  })
  ;
```

**The Component and Store**

``` js
import TheStore from './some-store-file';

var BaseComponent = {
  getStores () {
    return [ TheStore ];
  },

  getState () {
    return {
      name: TheStore.getValue()
    };
  },

  render () {
    return (<div>The test name is <b>{this.state.name}</b></div>);
  }
};

var Component = rStampit( React, BaseComponent ).compose( StoreConnector );

console.log( 'Markup: ', renderToStaticMarkup( <Component /> ) );
```

It's certainly not as clean as I'd like, but the component using the mixin is _relatively_ simple. This is workable, but does it give you any better ideas? I very much appreciate the help, gents!

**Comment by BerkeleyTrue** [comment]
@joshdmiller Have you heard of http://thundercats.js.org ( apologies for the shameless plug :)

**Comment by ericelliott** [comment]
Check out [redux](https://github.com/gaearon/redux) or [cerebral](https://github.com/christianalfoni/cerebral).

Cerebral needs some work, but it has a cool time travel debugger. Redux has the time travel debugging API, but doesn't have the neat UX (yet).

Redux has great integration with react hot reloader.

**Comment by troutowicz** [comment]
You don't need to use the stampit library for the mixin. React's `componentWillMount` lifecycle method behaves like stampit's `init`.

``` js
import React from 'react';
import stampit from 'react-stampit';

// store
const TheStore = {
  getValue() {
    return { name: 'foo' };
  },

  subscribe(cb) {
    console.log('Subscribed to store ' + this.getValue().name);
    //cb(updatedState);
  },
};

// mixin
const StoreConnector = {
  _handleStoreUpdates(updatedState) {
    this.setState(updatedState);
  },

  componentWillMount() {
    this.stores = this._getStores ? this._getStores() : [];
    this.storeSubscriptions = [];

    if (this._getState) {
      this.setState(this._getState());
    }

    this.stores.forEach(store => {
      this.storeSubscriptions.push(store.subscribe(this._handleStoreUpdates));
    });
  },

  componentWillUnmount() {
    this.storeSubscriptions.forEach(store => store.dispose());
  },
};

// component
const Component = stampit(React, {
  _getStores() {
    return [ TheStore ];
  },

  _getState() {
    return TheStore.getValue();
  },

  render() {
    return (<div>The store name is <b>{this.state.name}</b></div>);
  },
}).compose(StoreConnector);

console.log(React.renderToStaticMarkup(<Component />));
```

**Comment by troutowicz** [comment]
I'm not to sure why you need the `getState` method on the component though. This could be reduced to:

``` js
import React from 'react';
import stampit from 'react-stampit';

// store
const TheStore = {
  getValue() {
    return { name: 'foo' };
  },

  subscribe(cb) {
    console.log('Subscribed to store ' + this.getValue().name);
    //cb(updatedState);
  },
};

// mixin
var StoreConnector = {
  _handleStoreUpdates(updatedState) {
    this.setState(updatedState);
  },

  componentWillMount() {
    this.stores = this._getStores ? this._getStores() : [];
    this.storeSubscriptions = [];

    this.stores.forEach(store => {
      // do some sort of set state logic here
      this.setState(store.getValue());

      this.storeSubscriptions.push(store.subscribe(this._handleStoreUpdates));
    });
  },

  componentWillUnmount() {
    this.storeSubscriptions.forEach(store => store.dispose());
  },
};

// component
const Component = stampit(React, {
  _getStores() {
    return [ TheStore ];
  },

  render() {
    return (<div>The store name is <b>{this.state.name}</b></div>);
  },
}).compose(StoreConnector);

console.log(React.renderToStaticMarkup(<Component />));
```

**Comment by joshdmiller** [comment]
@BerkeleyTrue lol I read through the entire Thundercats source a couple days ago, but didn't make the connection to you until just now! I did like it (it's definitely well-written), but I was attempting a minimalist solution as an exercise. I am also trying to do it without a central dispatcher, which isn't easy without singletons. I looked at eight or nine libraries and Thundercats is my fallback.

@ericelliott  I'll take a look at redux at cerebral too. Thanks!

@troutowicz I think you're right about using `componentWillMount`, but I need to test a few more cases. The reason for the `getState()` is to allow multiple stores for a component and to re-call it when the props change (on the client). e.g.:

``` js
getStores () { return [ friendListStore, userStore ]; }

getState ( props ) {
  return {
    name: userStore.name,
    friends: friendListStore.friendsOf( props.id )
  };
}
```

This way, the component can get whatever state it needs from the stores and store it in whatever format makes sense for the component, and whenever the stores indicate they've changed (or if the props change from higher up the chain), the component can re-render what it needs to.

**Comment by ericelliott** [comment]
I like central dispatchers.

**Comment by joshdmiller** [comment]
What's your argument in favor of a central dispatcher? I don't feel very
strongly about it, but I often find the code less clear. E.g. `import
SavePost from`"../posts/save.action.js"` seems direct to me. I'd love to
be convinced because it makes some of the behind-the-scenes stuff
(particularly the isomorphic) a little easier to implement.

**Comment by ericelliott** [comment]
per client central authority gives easy command history features. https://www.youtube.com/watch?v=SiFwRtCnxv4

**Comment by BerkeleyTrue** [comment]
@joshdmiller Thanks! Not a fan of dispatcher either, but it would be nice to have a history. That is something I'm figuring out but it is not critical at the moment. When we start doing ab testing and customer support I'll be forced to add it in to make those easier. I'm adding features as the need becomes apparent.

**Comment by joshdmiller** [comment]
Hey guys - I've been on vacation for a while and am now diving back into things. I appreciate all the helpful comments and suggestions.

I think we can close this in favor of #31.
