### ISSUE TITLE
react-stampit with material-ui

### ISSUE THREAD

**Issue by gavriguy** [stampit-org/react-stampit#37]
I'm trying to implement react-stampit with material-ui
To set material-ui I need to set `getChildContext()` and `childContextTypes`.

for some reason when trying to so I get an error:

> uncaught Error: Invariant Violation: ReactStamp.getChildContext(): childContextTypes must be defined in order to use getChildContext().

here is the code i'm running

```
import stampit from 'react-stampit';
import { Styles, RaisedButton } from 'material-ui';

const ThemeManager = new Styles.ThemeManager();


export default React => stampit(React, {
  childContextTypes: {
    muiTheme: React.PropTypes.object,
  },
  getChildContext() {
    return {
      muiTheme: ThemeManager.getCurrentTheme()
    };
  },
  render() {
    return <div>
        <h1>Hello World</h1>
        <RaisedButton label="Click Me" />
      </div>
  }
});
```

Any idea what i'm doing wrong?

Thanks

**Comment by troutowicz** [comment]
Child context does not work with React v0.13.x. A React was [patch](https://github.com/facebook/react/pull/3940) was submitted and accepted a few months ago and will be included in React v0.14.

**Comment by gavriguy** [comment]
Thank you for that.
I think it would be good to mention this on the README file as known issues till its fixed.

**Comment by troutowicz** [comment]
It is mentioned already at the bottom of the README.

**Comment by gavriguy** [comment]
Sorry I didn't see it.
Thanks for your hard work. much appreciated.
